[10/06/2022]::[10:14:36]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/06/2022]::[10:20:30]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/06/2022]::[10:31:27]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/06/2022]::[16:04:01]::[COM=CONNECTION-STATUS]~~~~EMAIL-ERROR==EMAIL TEST FAILED 1.0~~::ADDRESS==['342']
[10/06/2022]::[16:11:30]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/06/2022]::[17:40:57]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 113, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n']
[10/06/2022]::[17:40:57]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 113, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:40:58]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:40:58]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:40:59]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:41:02]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:41:02]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:21]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 113, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n']
[10/06/2022]::[17:54:22]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:23]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:24]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:25]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:26]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:27]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:28]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:28]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 113, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n']
[10/06/2022]::[17:54:29]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:29]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:30]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:30]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:31]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:31]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:32]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:32]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:33]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:33]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:34]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:34]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:35]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:35]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:36]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:36]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:37]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:37]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:38]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:38]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:39]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:39]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:40]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:40]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:41]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:41]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:42]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:42]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:43]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:43]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:44]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:47]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[17:54:47]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[19:59:54]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/06/2022]::[20:03:20]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/06/2022]::[20:53:43]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 113, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:53:47]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 113, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:29]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 113, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n']
[10/06/2022]::[20:54:30]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:31]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:32]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:33]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:34]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:35]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:36]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:37]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:38]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/06/2022]::[20:54:41]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 173, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\n']
[10/07/2022]::[10:23:27]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/10/2022]::[12:13:49]::[COM=CONNECTION-STATUS]~~~~EMAIL-ERROR==EMAIL TEST FAILED 1.0~~::ADDRESS==['9792914660@tmomail.net']
[10/10/2022]::[12:16:13]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 282, in cred_enter\n    notify_user(\n', '  File ".\\coin-scout-V5.py", line 181, in notify_user\n    smtp.login(cred_enter.EMAIL_ADDR, cred_enter.EMAIL_PASS)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\smtplib.py", line 743, in login\n    raise last_exception\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\smtplib.py", line 732, in login\n    (code, resp) = self.auth(\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\smtplib.py", line 655, in auth\n    raise SMTPAuthenticationError(code, resp)\n']
[10/10/2022]::[12:19:58]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/10/2022]::[12:21:22]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/10/2022]::[12:26:29]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::[]
[10/10/2022]::[12:30:30]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 141, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 563, in send\n    raise SSLError(e, request=request)\n']
[10/10/2022]::[12:30:33]::[COM=CONNECTION-STATUS]~~~~ERROR == DISCONNECTED: 2~~NO INTERNET CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 202, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 563, in send\n    raise SSLError(e, request=request)\n']
[10/10/2022]::[12:30:36]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 202, in api_call\n    pinger = cg.ping()\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 63, in ping\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 563, in send\n    raise SSLError(e, request=request)\n']
[10/10/2022]::[12:31:10]::[COM=CONNECTION-STATUS]~~~~ERROR == CONNECTION DISCONNECTED: 333~~RETRYING CONNECTION~~
[DETAILS]::['  File ".\\coin-scout-V5.py", line 141, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n']
[10/10/2022]::[12:31:13]::[COM=CONNECTION-STATUS]~~~~SUCCESS == CONNECTED TO COINGECKO!!!  LETS GOOOOO{'gecko_says': '(V3) To the Moon!'}
[DETAILS]::['  File ".\\coin-scout-V5.py", line 141, in coinprice\n    coin_price = cg.get_price(ids=cred_coin.COIN, vs_currencies=cred_coin.CURRENCY)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\utils.py", line 12, in input_args\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 78, in get_price\n    return self.__request(api_url)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pycoingecko\\api.py", line 24, in __request\n    response = self.session.get(url, timeout=self.request_timeout)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 600, in get\n    return self.request("GET", url, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "C:\\Users\\db_admin1\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n']
